[global]
# Disables widget state duplication warnings
disableWidgetStateDuplicationWarning = true

# Disable warnings when running scripts directly
showWarningOnDirectExecution = false

[logger]
# Set logging level to 'info' to avoid verbose logging
level = "info"
# Standard logging format with timestamp
messageFormat = "%(asctime)s %(message)s"

[client]
# Hide detailed error messages and deprecation warnings in the browser
showErrorDetails = false
# Set toolbar visibility to minimal to reduce clutter
toolbarMode = "minimal"
# Disable sidebar navigation for a cleaner UI
showSidebarNavigation = false

[runner]
# Enable Streamlit's magic commands for ease of use
magicEnabled = true
# Handle rerun requests immediately for faster response times
fastReruns = true
# Ensure session state is serializable for consistent behavior across sessions
enforceSerializableSessionState = true
# Use name and value matching for Enum coercion to prevent issues during reruns
enumCoercion = "nameAndValue"

[server]
# Optimize file watcher settings for fewer reloads
fileWatcherType = "watchdog"
# Set cookie secret for consistent sessions across multiple instances
# cookieSecret = "b793e2eee09e155cf46cee55739c8f91a6e141fd8531e0dd5645c0dd7ad10552"
# Run the server in headless mode to prevent automatic browser pop-ups
headless = true
# Enable CORS and XSRF protection for security
enableCORS = true
enableXsrfProtection = true
# Adjust WebSocket settings for performance
enableWebsocketCompression = false
# Set server port and base URL
# port = 80
baseUrlPath = ""

[browser]
# Direct users to the correct server address
serverAddress = "localhost"
# Disable usage statistics for privacy
gatherUsageStats = false
# Align the serverPort with the actual port used by the server
serverPort = 80

[theme]
# Establish a consistent theme, change as per your design preference
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#333333"
font = "sans serif"
